
version: 2

models:
  - name: order_items
    description: "Items with augmented order information"
    columns:
      - name: line_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

